# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\tanalytics\"\x19\n\nAddRequest\x12\x0b\n\x03str\x18\x01 \x01(\t\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x42\n\nCalculator\x12\x34\n\x03\x41\x64\x64\x12\x15.analytics.AddRequest\x1a\x16.analytics.AddResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=31
  _globals['_ADDREQUEST']._serialized_end=56
  _globals['_ADDRESPONSE']._serialized_start=58
  _globals['_ADDRESPONSE']._serialized_end=87
  _globals['_CALCULATOR']._serialized_start=89
  _globals['_CALCULATOR']._serialized_end=155
# @@protoc_insertion_point(module_scope)
